# Train Test Split

## Import the relevant libraries

In [13]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate some data we are going to split

In [14]:
# arange is python built-in function for generate range between two numbers
a = np.arange(1,101)

In [15]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [16]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split the data

In [17]:
# take a array and split into two arrays
train_test_split(a)

[array([34, 62, 66, 21, 22, 24, 85,  9, 50, 36, 80, 29, 23, 10, 55, 97, 91,
         7,  6, 86, 54, 79, 30, 76, 43,  4, 33, 89, 48, 49, 37, 26, 81, 95,
        17, 98, 63, 93, 16, 59, 13, 32, 74, 44, 87, 88, 96, 65, 72, 12, 42,
        57, 18, 71, 27, 19, 92, 82, 45, 52, 68,  3, 14, 60,  1, 67, 15, 56,
        40, 38, 35, 46, 41, 94, 83]),
 array([ 11,  73,  78,  69,  53,   5,  61,   8,  20,  25,  84,  58,  99,
          2, 100,  75,  64,  77,  31,  70,  39,  90,  51,  47,  28])]

In [18]:
#first array is train 
#second array is test
#a_train, a_test = train_test_split(a)

In [19]:
#
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=365)

## Explore the result

In [20]:
a_train.shape, a_test.shape

((80,), (20,))

In [21]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [22]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [23]:
b_train.shape, b_test.shape

((80,), (20,))

In [24]:
b_train

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580])

In [25]:
b_test

array([581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593,
       594, 595, 596, 597, 598, 599, 600])